version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - 8000:8000
    depends_on:
      - db
    command: php artisan serve --host=127.0.0.1 --port=8000

  db:
    image: mysql
    container_name: mysql_db
    restart: always
    expose:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tcc
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
